/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team2.gooddriverincentiveprogram;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lizst
 */
public class AddDriver extends javax.swing.JFrame {

    /**
     * Creates new form CreateDriver
     */
    public AddDriver() {
        initComponents();
    }
    private int selectedCompID = -1;
    private int selectedDriverID = -1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DriverList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CompanyList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        addDriverToCompanyButton = new javax.swing.JButton();
        removeDriverFromCompanyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 49, 66));

        jPanel2.setBackground(new java.awt.Color(191, 192, 192));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Add/Remove Driver from a Company");

        DriverList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DriverList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                DriverListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(DriverList);

        jLabel2.setText("Select a Driver");

        CompanyList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CompanyList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                CompanyListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(CompanyList);

        jLabel3.setText("Select a Company");

        addDriverToCompanyButton.setText("Add Driver");
        addDriverToCompanyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDriverToCompanyButtonActionPerformed(evt);
            }
        });

        removeDriverFromCompanyButton.setText("Remove Driver");
        removeDriverFromCompanyButton.setToolTipText("");
        removeDriverFromCompanyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDriverFromCompanyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addDriverToCompanyButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeDriverFromCompanyButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 168, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(163, 163, 163))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDriverToCompanyButton)
                    .addComponent(removeDriverFromCompanyButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Helper method to populate the company list
    public void setCompanyList() throws SQLException {
        DefaultListModel model = new DefaultListModel(); //create a new list model

        PreparedStatement statement = MyConnection.getConnection().prepareStatement("Select * From Company");
        ResultSet resultSet = statement.executeQuery(); //run your query

        while (resultSet.next()) //go through each row that your query returns
        {
            String ItemList = resultSet.getInt("CompanyID") + ": " + resultSet.getString("CompanyName"); //get the element in column "item_code"
            model.addElement(ItemList); //add each item to the model
        }
        CompanyList.setModel(model);

        resultSet.close();
        statement.close();
    }     
    
    public void setDriverList() throws SQLException {
        DefaultListModel model = new DefaultListModel(); //create a new list model

        PreparedStatement statement = MyConnection.getConnection().prepareStatement("Select * From Users Where UserType='D'");
        ResultSet resultSet = statement.executeQuery(); //run your query

        while (resultSet.next()) //go through each row that your query returns
        {
            String ItemList = resultSet.getInt("UserID") + ": " + resultSet.getString("FirstName") + " " + resultSet.getString("MiddleName") + " " + resultSet.getString("LastName"); //get the element in column "item_code"
            model.addElement(ItemList); //add each item to the model
        }
        DriverList.setModel(model);

        resultSet.close();
        statement.close();
    }
    private void DriverListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_DriverListValueChanged
        String selectedDriver = DriverList.getSelectedValue();
        String [] tokens = selectedDriver.split(": ");
        selectedDriverID = Integer.parseInt(tokens[0]);
    }//GEN-LAST:event_DriverListValueChanged

    private void CompanyListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_CompanyListValueChanged
        String selectedCompany = CompanyList.getSelectedValue();
        String [] tokens = selectedCompany.split(": ");
        selectedCompID = Integer.parseInt(tokens[0]);
    }//GEN-LAST:event_CompanyListValueChanged

    private void addDriverToCompanyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDriverToCompanyButtonActionPerformed
        try {
            if(selectedCompID != -1 && selectedDriverID != -1) {

                int DID = getDriverID();

                //query for driver info from driver points
                PreparedStatement companyDriverPS = MyConnection.getConnection().prepareStatement("Select * From DriverPoints Where DriverID=? AND CompanyID=?");
                companyDriverPS.setInt(1, DID);
                //companyDriverPS.setInt(1, selectedDriverID);
                companyDriverPS.setInt(2, selectedCompID);
                ResultSet companyDriverRS = companyDriverPS.executeQuery();

                //Check to see if this driver already works for the company
                if(companyDriverRS.next()) {
                    JOptionPane.showMessageDialog(null, "Selected driver already works for selected company.", "Please try again", 2);
                }else{//insert the driver into the DriverPoints table
                    PreparedStatement DriverCreationPS = MyConnection.getConnection().prepareStatement("INSERT INTO DriverPoints (DriverID, CompanyID, Points) VALUES (?, ?, ?)");
                    //DriverCreationPS.setInt(1, selectedDriverID);
                    DriverCreationPS.setInt(1, DID);
                    DriverCreationPS.setInt(2, selectedCompID);
                    DriverCreationPS.setInt(3, 0);
                    DriverCreationPS.executeUpdate();
                    //Check to see if they have a pending application with the company they were just added to
                    PreparedStatement applicationCheckPS = MyConnection.getConnection().prepareStatement("SELECT * FROM DriverApplications WHERE DriverID=? AND CompanyID=?");
                    applicationCheckPS.setInt(1, DID);
                    applicationCheckPS.setInt(2, selectedCompID);
                    ResultSet applicationCheckRS = applicationCheckPS.executeQuery();
                    while(applicationCheckRS.next()) {
                        String status = applicationCheckRS.getString("ApplicationStatus");
                        if(status.equals("Pending")) {
                            PreparedStatement applicationUpdatePS = MyConnection.getConnection().prepareStatement("UPDATE DriverApplications SET ApplicationStatus=?, Reason=? WHERE DriverApplicationID=?");
                            applicationUpdatePS.setString(1, "Approved");
                            applicationUpdatePS.setString(2, "Approved by Admin");
                            applicationUpdatePS.setInt(3, applicationCheckRS.getInt("DriverApplicationID"));
                            applicationUpdatePS.executeUpdate();
                        }
                    }
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please make a company and driver selection.");
            }
        } catch(Exception e) {
            Logger.getLogger(AddDriver.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_addDriverToCompanyButtonActionPerformed

    private void removeDriverFromCompanyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDriverFromCompanyButtonActionPerformed
        try {
            if(selectedCompID != -1 && selectedDriverID != -1) {

                int DID = getDriverID();

                //query for driver info from driver points
                PreparedStatement companyDriverPS = MyConnection.getConnection().prepareStatement("Select * From DriverPoints Where DriverID=? AND CompanyID=?");
                companyDriverPS.setInt(1, DID);
                companyDriverPS.setInt(2, selectedCompID);
                ResultSet companyDriverRS = companyDriverPS.executeQuery();

                //Check to see if this driver already works for the company
                if(!companyDriverRS.next()) {
                    JOptionPane.showMessageDialog(null, "Selected driver doesn't work for selected company.", "Please try again", 2);
                }else{
                    //Delete the driver into the DriverPoints table
                    PreparedStatement DriverDeletionPS = MyConnection.getConnection().prepareStatement("DELETE FROM DriverPoints WHERE DriverID=? AND CompanyID=?");
                    DriverDeletionPS.setInt(1, DID);
                    DriverDeletionPS.setInt(2, selectedCompID);
                    DriverDeletionPS.executeUpdate();
                    //Check to see if they have an accepted application with the company they were just added to
                    PreparedStatement applicationCheckPS = MyConnection.getConnection().prepareStatement("SELECT * FROM DriverApplications WHERE DriverID=? AND CompanyID=?");
                    applicationCheckPS.setInt(1, DID);
                    applicationCheckPS.setInt(2, selectedCompID);
                    ResultSet applicationCheckRS = applicationCheckPS.executeQuery();
                    while(applicationCheckRS.next()) {
                        String status = applicationCheckRS.getString("ApplicationStatus");
                        if(status.equals("Approved")) {
                            PreparedStatement applicationUpdatePS = MyConnection.getConnection().prepareStatement("UPDATE DriverApplications SET ApplicationStatus=?, Reason=? WHERE DriverApplicationID=?");
                            applicationUpdatePS.setString(1, "Revoked");
                            applicationUpdatePS.setString(2, "Revoked by Admin");
                            applicationUpdatePS.setInt(3, applicationCheckRS.getInt("DriverApplicationID"));
                            applicationUpdatePS.executeUpdate();
                        }
                    }
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please make a company and driver selection.");
            }
        } catch(Exception e) {
            Logger.getLogger(AddDriver.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_removeDriverFromCompanyButtonActionPerformed
    
    private int getDriverID() throws SQLException{
                // Get the driverID
                int ID = 0;
                PreparedStatement DriverPS = MyConnection.getConnection().prepareStatement("Select DriverID From Driver Where UserID=?");
                DriverPS.setInt(1, selectedDriverID);
                ResultSet DriverRS = DriverPS.executeQuery();
                if(DriverRS.next()){
                    ID = DriverRS.getInt("DriverID");
                }
        return ID;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> CompanyList;
    private javax.swing.JList<String> DriverList;
    private javax.swing.JButton addDriverToCompanyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeDriverFromCompanyButton;
    // End of variables declaration//GEN-END:variables
}
